# Generated by Django 3.0.4 on 2021-08-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
