# Generated by Django 3.0.4 on 2021-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210822_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
