# Generated by Django 3.0.4 on 2021-08-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210822_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color1',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
