# Generated by Django 3.0.4 on 2021-08-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210823_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color1',
        ),
        migrations.AddField(
            model_name='product',
            name='red',
            field=models.BooleanField(default=True),
        ),
    ]
