# Generated by Django 3.0.4 on 2021-08-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210823_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='black',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='blue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='green',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='orange',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pink',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purple',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='white',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='yellow',
            field=models.BooleanField(default=True),
        ),
    ]
