# Generated by Django 3.0.4 on 2021-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210824_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size6',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
