# Generated by Django 3.0.4 on 2021-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20210824_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
