# Generated by Django 3.0.4 on 2021-08-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_product_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
