# Generated by Django 3.0.4 on 2021-08-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(blank=True, max_length=200, null=True),
        ),
    ]
