# Generated by Django 3.0.4 on 2021-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20210825_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
