# Generated by Django 3.0.4 on 2021-08-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20210825_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color10',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_10',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
