# Generated by Django 3.0.4 on 2021-08-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20210825_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('date_and_time_of_purchasing', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
