# Generated by Django 3.0.4 on 2021-08-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='date_and_time_of_purchasing',
            field=models.CharField(max_length=55),
        ),
    ]
